### ISSUE TITLE
Некорректный спецификатор доступа

### ISSUE THREAD

**Issue by truenorthpaul** [Pasha1N/WaterPipes#24]
Спецификаторы доступа должны быть как можно более защищенными для каждого члена класса или структуры. В качестве исключения можно использовать `public` вместо `internal` если весь тип содержащий данный член помечен спецификатором `internal`.

Поля, для которых данное правило не соблюдается:
- `WaterPipes.Game.ElementsOfThePipeline.height`.
- `WaterPipes.Game.ElementsOfThePipeline.width`.

**Comment by truenorthpaul** [comment]
Надо было изменить на `private`.

**Comment by Pasha1N** [comment]
а как с наследниками?

**Comment by truenorthpaul** [comment]
Поля должны быть приватными. Без вариантов. Наследники могут обращаться через свойства, например.

**Comment by Pasha1N** [comment]
то есть к этим полям можно будет обращаться через свойства?

**Comment by truenorthpaul** [comment]
Если эти свойства будут объявлены в классе с самими полями, то да.
