### ISSUE TITLE
Использование наиболее базового интерфейса

### ISSUE THREAD

**Issue by truenorthpaul** [Pasha1N/WaterPipes#26]
При выборе типа константы, поля, параметра, возвращаемого значения или переменной необходимо отдавать предпочтение наиболее базовому интерфейсу, который обладает требуемой функциональностью. Другими словами, не стоит использовать в качестве типа параметра метода тип `List<string>` если метод использует данный параметр только для обхода коллекции элементов. В такой ситуации достаточно было бы использовать тип `IEnumerable<string>`.

Поля, для которых данное правило не соблюдается:
- `WaterPipes.Game.InstallationOfPipelineComponents.pipes`.
- `WaterPipes.Game.InstallationOfPipelineComponents.sources`.
- `WaterPipes.Game.StartGame.pipes`.
- `WaterPipes.Game.StartGame.sources`.

Параметры, для которых данное правило не соблюдается:
- `pipes` (метод `WaterPipes.Game.InstallationOfPipelineComponents.InstallationOfPipelineComponents`).
- `sources` (метод `WaterPipes.Game.InstallationOfPipelineComponents.InstallationOfPipelineComponents`).

**Comment by Pasha1N** [comment]
pipes (метод WaterPipes.Game.InstallationOfPipelineComponents.InstallationOfPipelineComponents).
sources (метод WaterPipes.Game.InstallationOfPipelineComponents.InstallationOfPipelineComponents). 
там параметры принимаются через интерфейс!
