### ISSUE TITLE
Неинформативные идентификаторы

### ISSUE THREAD

**Issue by truenorthpaul** [Pasha1N/WaterPipes#32]
Идентификаторы должны быть информативны и описывать свое предназначение. 

Пространства имен, для идентификаторов которых данное правило не соблюдается:
- `WaterPipes.Game.MyTypes`.

Классы, для идентификаторов которых данное правило не соблюдается:
- `WaterPipes.Game.MyTypes.Bool`.

**Comment by Pasha1N** [comment]
куда еще информативнее ?
это обычный bool тока он не структурный а ссылочный тип ?

**Comment by Pasha1N** [comment]
можно назвать его boolean?

**Comment by truenorthpaul** [comment]
Поля, для идентификаторов которых данное правило не соблюдается:
- `WaterPipes.Game.ManagementOfWork.@bool.`

Свойства, для идентификаторов которых данное правило не соблюдается:
- `WaterPipes.Game.ManagementOfWork.Value.`

**Comment by truenorthpaul** [comment]
Свойства, для идентификаторов которых данное правило не соблюдается:
- `WaterPipes.Game.ManagementOfWork.Value`.
